version: '3.8'

services:
  frontend:
    build:
      context: ../lostcities-frontend
    volumes:
      - ../lostcities-frontend:/usr/src/lostcities
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.5

  accounts:
    container_name: accounts
    image: dereknelson.io/library/lostcities-accounts
    environment:
      SPRING_PROFILES_ACTIVE: dev
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    depends_on:
    #  - spring-cloud-config-server
      - accounts-database
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.10

  accounts-database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: accounts
      POSTGRES_PASSWORD: example
      POSTGRES_DB: lostcities-accounts
    expose:
      - 5432
    volumes:
      - accounts_postgres_data:/var/lib/postgresql/data/
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.15

  matches:
    container_name: matches
    image: dereknelson.io/library/lostcities-matches
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
    #  - spring-cloud-config-server
      - accounts-database
      - rabbitmq
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.20

  matches-database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: matches
      POSTGRES_PASSWORD: example
      POSTGRES_DB: lostcities-matches
    volumes:
      - matches_postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.25

  gamestate:
    container_name: gamestate
    image: dereknelson.io/library/lostcities-gamestate
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
    #  - spring-cloud-config-server
      - redis
      - rabbitmq
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.30

  player-events:
    container_name: player-events
    image: dereknelson.io/library/lostcities-player-events
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
    #  - spring-cloud-config-server
      - rabbitmq
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.35

  rabbitmq:
    image: rabbitmq:3-management-alpine
    expose:
      - 5672
      - 15672
    volumes:
      - rabbit_data:/var/lib/rabbitmq/
    #  - /var/lib/rabbitmq/log/:/var/log/rabbitmq/
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.60

  redis:
    image: redislabs/redismod
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    working_dir: /data
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.61

volumes:
  grafana-storage:
    external: true
    name: grafana-storage
  matches_postgres_data:
    external: true
    name: matches_postgres_data
  accounts_postgres_data:
    external: true
    name: accounts_postgres_data
  redis_data:
    external: true
    name: redis_data
  rabbit_data:
    external: true
    name: rabbit_data

networks:
  lostcities-network:
    ipam:
      config:
        - subnet: 172.20.0.0/24