version: '2'
services:
  nginx:
    build:
      context: ./nginx
    environment:
      #- NGINX_HOST=lostcities.com
      - NGINX_PORT=80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - accounts
      - matches
      - frontend
    networks:
      java:
        ipv4_address: 172.20.0.5
  frontend:
    container_name: frontend
    build:
      context: ../lostcities-frontend
    volumes:
      - ../lostcities-frontend:/usr/src/lostcities
    networks:
      java:
        ipv4_address: 172.20.0.6
  accounts:
    build:
      context: ../lostcities-accounts
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE}
    volumes:
      - ../lostcities-accounts:/accounts
      - ../lostcities-common:/lostcities-common
    depends_on:
      - accounts-database
    networks:
      java:
        ipv4_address: 172.20.0.10
  matches:
    build:
      context: ../lostcities-matches
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE}
    volumes:
      - ../lostcities-matches:/matches
      - ../lostcities-common:/lostcities-common
    networks:
      java:
        ipv4_address: 172.20.0.20
    depends_on:
      - kafka
      - accounts-database
  accounts-database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: accounts
      POSTGRES_PASSWORD: example
      POSTGRES_DB: lostcities-accounts
      PGDATA: /var/lib/postgresql/data/accounts
    expose:
      - 5432
    networks:
      java:
        ipv4_address: 172.20.0.30
  matches-database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: matches
      POSTGRES_PASSWORD: example
      POSTGRES_DB: lostcities-matches
      PGDATA: /var/lib/postgresql/data/accounts
    expose:
      - 5432
    networks:
      java:
        ipv4_address: 172.20.0.40
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - 2181
    networks:
      java:
        ipv4_address: 172.20.0.55

  kafka:
    image: wurstmeister/kafka
    expose:
      - 9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "create-game-topic:1:1" #,command-job-topic:1:1,game-change-notification-topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: 172.20.0.55:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      java:
        ipv4_address: 172.20.0.50
networks:
  java:
    ipam:
      config:
        - subnet: 172.20.0.0/24