version: '2'
services:
  nginx:
    build:
      context: ./nginx
    environment:
      #- NGINX_HOST=lostcities.com
      - NGINX_PORT=80
    #volumes:
    #  - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - accounts
      - matches
      - frontend
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "create-game-topic:1:1" #,command-job-topic:1:1,game-change-notification-topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  # lostcities-web-experience:
  #   build:
  #     context: ../lostcities-web-experience
  #   working_dir: /lost-cities
  #   command: bash -c "chmod +x ./gradlew && ./gradlew bootRun"
  #   ports:
  #     - "8081:8080"
  #   volumes:
  #     - ../lostcities-web-experience:/lost-cities
  #     - ../lostcities-common:/lostcities-common
  accounts:
    build:
      context: ../lostcities-accounts
    working_dir: /accounts
    command: bash -c "chmod +x ./gradlew && SPRING_PROFILES_ACTIVE=${PROFILE} ./gradlew bootRun"
    volumes:
      - ../lostcities-accounts:/accounts
      - ../lostcities-common:/lostcities-common
    depends_on:
      - accounts-database
  accounts-database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: accounts
      POSTGRES_PASSWORD: example
      POSTGRES_DB: lostcities-accounts
      PGDATA: /var/lib/postgresql/data/accounts
    ports:
      - "5432:5432"
  matches:
    build:
      context: ../lostcities-matches
    working_dir: /matches
    command: bash -c "chmod +x ./gradlew && SPRING_PROFILES_ACTIVE=${PROFILE} ./gradlew bootRun"
    volumes:
      - ../lostcities-matches:/matches
      - ../lostcities-common:/lostcities-common
    depends_on:
      - kafka
      - accounts-database
  matches-database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: matches
      POSTGRES_PASSWORD: example
      POSTGRES_DB: lostcities-matchesAdding clone for frontend.
      PGDATA: /var/lib/postgresql/data/accounts
  frontend:
    container_name: frontend
    build:
      context: ../lostcities-frontend
    volumes:
      - ../lostcities-frontend:/usr/src/lostcities
    expose:
      - 8080

#  lostcities-command-processor:
#    build:
#      context: ../lost-cities-command-processor
#    command: bash -c "chmod 777 ./gradlew && ./gradlew bootRun"
#    volumes:
#      - ../lost-cities-command-processor:/lost-cities-command-processor
#      - ../lostcities-common:/lostcities-common