version: '2'
services:
  frontend:
    container_name: frontend
    build:
      context: ../lostcities-frontend
    volumes:
      - ../lostcities-frontend:/usr/src/lostcities
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.5
  accounts:
    image: dereknelson.io/library/lostcities-accounts
    environment:
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - ../lostcities-accounts:/accounts
      - /var/lib/gradle/accounts:/accounts/.gradle
    depends_on:
      - accounts-database
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.10
  accounts-database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: accounts
      POSTGRES_PASSWORD: example
      POSTGRES_DB: lostcities-accounts
      PGDATA: /var/lib/postgresql/data/accounts
    expose:
      - 5432
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.15
  matches:
    image: dereknelson.io/library/lostcities-matches
    environment:
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - ../lostcities-matches:/matches
      - /var/lib/gradle/matches:/matches/.gradle
    depends_on:
      - accounts-database
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.20
  matches-database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: matches
      POSTGRES_PASSWORD: example
      POSTGRES_DB: lostcities-matches
      PGDATA: /var/lib/postgresql/data/matches
    expose:
      - 5432
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.25
  gamestate:
    image: dereknelson.io/library/lostcities-gamestate
    environment:
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - ../lostcities-gamestate:/gamestate
      - /var/lib/gradle/gamestate:/gamestate/.gradle
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.30

  player-events:
    image: dereknelson.io/library/lostcities-player-events
    environment:
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - ../lostcities-player-events:/player-events
      - /var/lib/gradle/player-events:/player-events/.gradle
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.35
  rabbitmq:
    image: rabbitmq:3-management-alpine
    expose:
      - 5672
      - 15672
    #volumes:
    #  - /var/lib/rabbitmq/data/:/var/lib/rabbitmq/
    #  - /var/lib/rabbitmq/log/:/var/log/rabbitmq/
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.60
  redis:
    image: redislabs/redismod
    ports:
      - 6379:6379
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.61
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    # volumes:
    #   - ${APPLICATION_DATA_DIR}/redisinsight:/db
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.62
networks:
  lostcities-network:
    ipam:
      config:
        - subnet: 172.20.0.0/24