version: '2'
services:
  nginx:
    build:
      context: ./nginx
    environment:
      - NGINX_PORT=80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - accounts
      - matches
      - gamestate
      - frontend
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.2
  frontend:
    container_name: frontend
    build:
      context: ../lostcities-frontend
    volumes:
      - ../lostcities-frontend:/usr/src/lostcities
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.5
  accounts:
    build:
      context: ../lostcities-accounts
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE}
    volumes:
      - ../lostcities-accounts:/accounts
      - /var/lib/gradle/accounts:/accounts/.gradle
    depends_on:
      - accounts-database
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.10
  accounts-database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: accounts
      POSTGRES_PASSWORD: example
      POSTGRES_DB: lostcities-accounts
      PGDATA: /var/lib/postgresql/data/accounts
    expose:
      - 5432
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.15
  matches:
    build:
      context: ../lostcities-matches
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE}
    volumes:
      - ../lostcities-matches:/matches
      - /var/lib/gradle/matches:/matches/.gradle
    depends_on:
      - accounts-database
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.20
  matches-database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: matches
      POSTGRES_PASSWORD: example
      POSTGRES_DB: lostcities-matches
      PGDATA: /var/lib/postgresql/data/matches
    expose:
      - 5432
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.25
  gamestate:
    build:
      context: ../lostcities-gamestate
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE}
    volumes:
      - ../lostcities-gamestate:/gamestate
      - /var/lib/gradle/gamestate:/gamestate/.gradle
    depends_on:
      - gamestate-database
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.30
  gamestate-database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: gamestate
      POSTGRES_PASSWORD: example
      POSTGRES_DB: lostcities-gamestate
      PGDATA: /var/lib/postgresql/data/gamestate
    expose:
      - 5432
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.35
  rabbitmq:
    image: rabbitmq:3-management-alpine
    expose:
      - 5672
      - 15672
    #volumes:
    #  - /var/lib/rabbitmq/data/:/var/lib/rabbitmq/
    #  - /var/lib/rabbitmq/log/:/var/log/rabbitmq/
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.60
networks:
  lostcities-network:
    ipam:
      config:
        - subnet: 172.20.0.0/24