version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "command-job-topic:1:1,game-change-notification-topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  lostcities-web-experience:
    build:
      context: ../lostcities-web-experience
    working_dir: /lost-cities
    command: bash -c "chmod 777 ./gradlew && ./gradlew bootRun"
    ports:
      - "8080:8080"
    volumes:
      - ../lostcities-web-experience:/lost-cities
      - ../lostcities-common:/lostcities-common
    depends_on:
      - kafka
  #lostcities-command-processor:
  #  build:
  #    context: ../lost-cities-command-processor
  #  command: bash -c "chmod 777 ./gradlew && ./gradlew bootRun"
  #  volumes:
  #    - ../lost-cities-command-processor:/lost-cities-command-processor
  #    - ../lostcities-common:/lostcities-common