version: '2'
services:
  nginx:
    build:
      context: ./nginx
    environment:
      - NGINX_PORT=80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - accounts
      - matches
      - frontend
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.2
  frontend:
    container_name: frontend
    build:
      context: ../lostcities-frontend
    volumes:
      - ../lostcities-frontend:/usr/src/lostcities
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.5
  accounts:
    build:
      context: ../lostcities-accounts
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE}
    volumes:
      - ../lostcities-accounts:/accounts
      - ../lostcities-common:/lostcities-common
    depends_on:
      - accounts-database
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.10
  accounts-database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: accounts
      POSTGRES_PASSWORD: example
      POSTGRES_DB: lostcities-accounts
      PGDATA: /var/lib/postgresql/data/accounts
    expose:
      - 5432
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.15
  matches:
    build:
      context: ../lostcities-matches
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE}
    volumes:
      - ../lostcities-matches:/matches
      - ../lostcities-common:/lostcities-common
    depends_on:
      - accounts-database
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.20
  matches-database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: matches
      POSTGRES_PASSWORD: example
      POSTGRES_DB: lostcities-matches
      PGDATA: /var/lib/postgresql/data/accounts
    expose:
      - 5432
    networks:
      lostcities-network:
        ipv4_address: 172.20.0.25
#  rabbitmq:
#    image: rabbitmq:3-management-alpine
#    container_name: 'rabbitmq'
#    export:
#      - 5672
#      - 15672
#    volumes:
#      - /var/lib/rabbitmq/data/:/var/lib/rabbitmq/
#      - /var/lib/rabbitmq/log/:/var/log/rabbitmq
#    networks:
#      lostcities-network:
#        ipv4_address: 172.20.0.50
networks:
  lostcities-network:
    ipam:
      config:
        - subnet: 172.20.0.0/24