server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/log/lostcities/*log

    pipeline_stages:
      - regex:
          expression: ^(?P<timestamp>\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d,\d*)\sapplication=(?P<application>[a-zA-Z]+)\sprofiles=(?P<profiles>[a-zA-Z]+)\s(?P<level>[A-Z]{4,5})\s\[(?P<thread>.*?)\]\s(?P<logger>.*?)\s\:\s(?P<message>.*?)$
          source: tag
          labels:
            timestamp:
            application:
            profiles:
            level:
            thread:
            logger:
            message:
      - timestamp:
          format: RFC3339Nano
          source: time
      - output:
          source: output